---

- name: "Create ssh key at VSD"
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa
  remote_user: root

- name: "Fetch ssh public from VSD"
  fetch: src=/root/.ssh/id_rsa.pub dest=/tmp
  remote_user: root

- name: "Add stat to VSD known_hosts list"
  shell: "ssh-keyscan -t rsa {{ hostvars[groups['stat'][0]].interfaces[0].ip }} | sed -e 's/#.*$//' | sed -e '/^$/d' > /root/.ssh/known_hosts"
  remote_user: root
  when: hostvars[ groups['stat'][0]].interfaces[0].ip is defined

- name: "Add util to VSD known_hosts list"
  shell: "ssh-keyscan -t rsa {{ hostvars[groups['util'][0]].interfaces[0].ip }} | sed -e 's/#.*$//' | sed -e '/^$/d' > /root/.ssh/known_hosts"
  remote_user: root
  when: hostvars[ groups['util'][0]].interfaces[0].ip is defined

